### ISSUE TITLE
Match routes to a regex

### ISSUE THREAD

**Issue by foikila** [mosbth/anax#2]
Make it possible to add routes with a regex. 

Example:

```
$app->router->add('/some/route/([0-9]+)', function()  use($app) {
}
```

It would be really nice if an user could define own "aliases" for complicated regex (not the my examples are complicated).

Like something like this:

```
[
    ':id' => '([0-9]+)',
    ':string' => '([a-b])'
]
```

Then you can use the user defined regex like this

```
$app->router->add('/some/route/:id', function()  use($app) {
}
```

**Comment by mosbth** [comment]
Ok, lets get inspiration from here, before deciding on how to implement it:
http://docs.phalconphp.com/en/latest/reference/routing.html
http://laravel.com/docs/5.0/routing
http://symfony.com/doc/current/book/routing.html
http://book.cakephp.org/3.0/en/development/routing.html
